### ISSUE TITLE
Properties in FlexDataTypes not memory safe

### ISSUE THREAD

**Issue by markltownsend** [nairteashop/CocoaAMF#1]
The updater of this library removed all the "retain" attributes from the @properties, but the default is "assign" which is bad.  "retain" should be replaced by "strong" when converting to ARC.  This fork is not useful in a production environment.

**Comment by nairteashop** [comment]
"retain" was removed automatically by the XCode "validate project settings" tool. It did that because, contrary to your comment, the equivalent "strong" is the default in ARC and has been the case for a while.

Some references:
- [Transitioning to ARC](https://developer.apple.com/library/ios/releasenotes/ObjectiveC/RN-TransitioningToARC/Introduction/Introduction.html#//apple_ref/doc/uid/TP40011226-CH1-SW4)
- [Programming with Objective-C](https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/EncapsulatingData/EncapsulatingData.html#//apple_ref/doc/uid/TP40011210-CH5-SW30)
- [Automatic Reference Counting](http://clang.llvm.org/docs/AutomaticReferenceCounting.html#property-declarations)
